# Site settings
title: Ant Meehan
email: mail@antmeehan.com
description: "Ramblings from a software developer"
baseurl: ""
url: "http://antmeehan.com"
twitter_username: antmeehan
github_username:  antmeehan
facebook_username:  Anthony.Meehan

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
