# Site settings
title: Ant Meehan
email: mail@antmeehan.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://antmeehan.com/"
twitter_username: antmeehan
github_username:  antmeehan
facebook_username:  Anthony.Meehan

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
